apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: 6dda090f45d6a4f241712623b21e2c03f5f68e1c
    application.deploy.reform/deploymentNo: test-ops-222-local-approval_DP5
    application.deploy.reform/environment: local-approval
    application.deploy.reform/name: test-ops-222
    application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
    application.deploy.reform/repositoryPath: "006"
    application.deploy.reform/revision: 2023.04.5
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 6b5c82cf8fbd6720e41370072c0193f4158e3f6c
  creationTimestamp: null
  name: test-ops-222
  namespace: vela-app
spec:
  components:
  - dependsOn:
    - test-ops-222-newinfra-infrastructure
    name: test-ops-222-newhelm-api
    properties:
      domain: https://github.com/lilian-resolve/test-de-001
      expose: true
      path: "005"
      resource: Low
      secure: true
    type: web-wizard-api
  - name: test-ops-222-newinfra-infrastructure
    properties:
      resource: Low
      size: true
    type: web-wizard-db
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
