apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: test-ops-001
  namespace: vela-app
spec:
  components:
  - name: test-ops-001-web-wizard-web-web
    properties:
      domain: https://github.com/lilian-resolve/test-de-001.git
      path: "004"
      resource: Low
      secure: true
    type: web-wizard-web
  - name: test-ops-001-newweb-api
    properties:
      domain: https://github.com/lilian-resolve/test-de-001
      expose: false
      path: "004"
      resource: Low
      secure: false
    type: web-wizard-api
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
