apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 4f548b355a1f7491d8d6982802709581eead173f
  application.deploy.reform/deploymentNo: qc-trial-001-local-approval_DP4
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: qc-trial-001
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: "013"
  application.deploy.reform/revision: 2023.04.4
  deploy.reform/domain: ""
  deploy.reform/version: 43e386f1506722b87e678ebb8547dd6b12ad3381
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
