apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: b17076c5a20a49cd7969c0787b6cfb82130dfa82
  application.deploy.reform/deploymentNo: qc-trial-001-local-approval_DP1
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: qc-trial-001
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: "013"
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: f86b2b7d87415d091966ec0d2e4c54a54d294db7
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
