apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: test-ops-222
  namespace: vela-app
spec:
  components:
  - name: test-ops-222-web-wizard-web-web
    properties:
      domain: https://github.com/lilian-resolve/test-de-001
      path: "005"
      resource: Low
      secure: true
    type: web-wizard-web
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
