apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: e2f4192025dc72327e8e2a7acb8726e5cc2edd7c
    application.deploy.reform/deploymentNo: qc-fail-001-local-approval_DP4
    application.deploy.reform/environment: local-approval
    application.deploy.reform/name: qc-fail-001
    application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
    application.deploy.reform/repositoryPath: "010"
    application.deploy.reform/revision: 2023.04.4
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 81b5e90dee2da07e72eae3cc46a074f9156e8da8
  creationTimestamp: null
  name: qc-fail-001
  namespace: vela-app
spec:
  components:
  - name: qc-fail-001-fail01-web
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 1Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
