apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: b8304cc90b6745fde29d10ab07805c8fdcfc35e1
  application.deploy.reform/deploymentNo: qc-trial-001-local_DP3
  application.deploy.reform/environment: local
  application.deploy.reform/name: qc-trial-001
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-trial-001
  application.deploy.reform/revision: 2023.04.3
  deploy.reform/domain: ""
  deploy.reform/version: 1dbda0156a3037557aa268950c309e5bbbc2f057
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
