apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 057aea6457b9fbe2db0fc3eefb93b607b6653b18
  application.deploy.reform/deploymentNo: wizard-test-1-local_DP1
  application.deploy.reform/environment: local
  application.deploy.reform/name: wizard-test-1
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: wizard-test-1
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: f86b2b7d87415d091966ec0d2e4c54a54d294db7
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
