apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 5632b9c40184a2e130a5b69da14848efc11bb7a2
  application.deploy.reform/deploymentNo: qc-demo-004-dev-approval_DP2
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: qc-demo-004
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: qc-demo-004
  application.deploy.reform/revision: 2023.04.2
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
