apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 34f340195b6177f41b7a7d20f34796e395829bd4
  application.deploy.reform/deploymentNo: qc-dev-001-local-approval_DP5
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: qc-dev-001
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-dev-001
  application.deploy.reform/revision: 2023.04.5
  deploy.reform/domain: ""
  deploy.reform/version: c5bd33c126af95320d9d4ca06e6b80718af3c856
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
