apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: fcdf4ebce90d83a2de6816d7e259df134d53b9ac
  application.deploy.reform/deploymentNo: qc-run-01-local-approval_DP1
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: qc-run-01
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-run-01
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: 588550c7da8671ad490dc07da3791dfd9b6d99b3
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
