apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: e4247d1c1899a86dba2d77dc9af573f805e45daf
  application.deploy.reform/deploymentNo: qc-demo-002-dev-approval_DP2
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: qc-demo-002
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: qc-demo-002
  application.deploy.reform/revision: 2023.04.2
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
