apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 8cb3a9b215b3d19aee1216daeb9619ea8d564238
  application.deploy.reform/deploymentNo: qc-demo-002-dev-approval_DP1
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: qc-demo-002
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: qc-demo-002
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
