apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 262fd158dcc6a788f1e9738087ded2dacd23a0af
  application.deploy.reform/deploymentNo: qc-deploy-001-dev-approval_DP3
  application.deploy.reform/environment: dev-approval
  application.deploy.reform/name: qc-deploy-001
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: qc-deploy-001
  application.deploy.reform/revision: 2023.04.3
  deploy.reform/domain: ""
  deploy.reform/version: ccc38202e745330f431bb2ca42601632c9e3fb12
kind: Kustomization
namespace: uat
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
