apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 36db1be04ccb648cabc3d89ecf69150dc4642126
  application.deploy.reform/deploymentNo: qc-trial-003-local_DP2
  application.deploy.reform/environment: local
  application.deploy.reform/name: qc-trial-003
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-trial-003
  application.deploy.reform/revision: 2023.04.2
  deploy.reform/domain: ""
  deploy.reform/version: 588550c7da8671ad490dc07da3791dfd9b6d99b3
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
