apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: cde1f152f02fb7ffe211ebb84bd80f028e4c326d
    application.deploy.reform/deploymentNo: qc-name-01-local_DP1
    application.deploy.reform/environment: local
    application.deploy.reform/name: qc-name-01
    application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
    application.deploy.reform/repositoryPath: "009"
    application.deploy.reform/revision: 2023.04.1
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 97a8dfd5397e881e69d246ac1cba15eb5fd08c3b
  creationTimestamp: null
  name: qc-name-01
  namespace: vela-app
spec:
  components:
  - name: qc-name-01-newweb-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: docker-pull.infinity.reslv.one/nginx
      imagePullPolicy: IfNotPresent
      memory: 10Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
