apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: bc06f32604b7d1e23f36a0904091c80544216ad3
    application.deploy.reform/deploymentNo: test-ops-333-local_DP2
    application.deploy.reform/environment: local
    application.deploy.reform/name: test-ops-333
    application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
    application.deploy.reform/repositoryPath: "007"
    application.deploy.reform/revision: 2023.04.2
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 6b5c82cf8fbd6720e41370072c0193f4158e3f6c
  creationTimestamp: null
  name: test-ops-333
  namespace: vela-app
spec:
  components:
  - name: test-ops-333-newweb-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 1024Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  - name: test-ops-333-newwebb-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: docker
      imagePullPolicy: IfNotPresent
      memory: 100Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
