apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: Test-test
  creationTimestamp: null
  name: qc-demo-001
  namespace: vela-system
spec:
  components:
  - name: qc-demo-001-newweb-web
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: docker-pull.infinity.reslv.one/nginx
      imagePullPolicy: IfNotPresent
      memory: 10Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
