apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 1feb015b3d90da06f1b5340eea82dd1f1b2f6887
  application.deploy.reform/deploymentNo: qc-trial-003-local-approval_DP1
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: qc-trial-003
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: "016"
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: f86b2b7d87415d091966ec0d2e4c54a54d294db7
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
