apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: qc-recover-002
  namespace: vela-system
spec:
  components:
  - name: qc-recover-002-newweb-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: docker-pull.infinity.reslv.one/nginx
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - docker-pull.infinity.reslv.one
      memory: 9Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
status: {}
