apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 753101f42de121e418196ebd23494699769ae22d
  application.deploy.reform/deploymentNo: qc-trial-002-local_DP3
  application.deploy.reform/environment: local
  application.deploy.reform/name: qc-trial-002
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001.git
  application.deploy.reform/repositoryPath: "014"
  application.deploy.reform/revision: 2023.04.3
  deploy.reform/domain: ""
  deploy.reform/version: f86b2b7d87415d091966ec0d2e4c54a54d294db7
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
