apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: qc-trial-002
  namespace: vela-system
spec:
  components:
  - name: qc-trial-002-newweb-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: docker-pull.infinity.reslv.one/nginx
      imagePullPolicy: IfNotPresent
      memory: 16Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  - name: qc-trial-002-app-test-web
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 1024Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
status: {}
