apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 59551be11a2a313ea2f9598a08f23bbb731ff8a6
  application.deploy.reform/deploymentNo: qc-applist-002-local_DP3
  application.deploy.reform/environment: local
  application.deploy.reform/name: qc-applist-002
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-applist-002
  application.deploy.reform/revision: 2023.04.3
  deploy.reform/domain: ""
  deploy.reform/version: e81b9acf0e7ba35a992597ab6fb5d5564a7895b8
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
