apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: nc-1
  creationTimestamp: null
  name: app-testwe
  namespace: vela-system
spec:
  components:
  - name: app-testwe-ng-web
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: docker-pull.infinity.reslv.one/nginx
      imagePullPolicy: IfNotPresent
      memory: 10Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
status: {}
