apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: b59c8b6cdd2dfd942624b215688d6fcfc7cba289
  application.deploy.reform/deploymentNo: qc-testtag-01-local_DP1
  application.deploy.reform/environment: local
  application.deploy.reform/name: qc-testtag-01
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-testtag-01
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: 588550c7da8671ad490dc07da3791dfd9b6d99b3
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
