apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: ab870ff4a8a1915e17624972ec945dde8ebc99ef
  application.deploy.reform/deploymentNo: qc-recover-002-local_DP1
  application.deploy.reform/environment: local
  application.deploy.reform/name: qc-recover-002
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-recover-002
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: e81b9acf0e7ba35a992597ab6fb5d5564a7895b8
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
