apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: test-ops-111
  namespace: vela-system
spec:
  components:
  - name: test-ops-111-web-wizard-web-web
    properties:
      domain: https://github.com/lilian-resolve/test-de-001.git
      path: "001"
      resource: Low
      secure: true
    type: web-wizard-web
status: {}
