apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: ecc795f440d74182a230a414e2bcd6c588d16508
  application.deploy.reform/deploymentNo: qc-trial-005-local_DP1
  application.deploy.reform/environment: local
  application.deploy.reform/name: qc-trial-005
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-trial-005
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: 588550c7da8671ad490dc07da3791dfd9b6d99b3
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
