apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: test-ops-222
  namespace: vela-system
spec:
  components:
  - name: test-ops-222-newhelm-api
    properties:
      domain: https://github.com/lilian-resolve/test-de-001
      expose: true
      path: "005"
      resource: Low
      secure: true
    type: web-wizard-api
  - name: test-ops-222-newinfra-infrastructure
    properties:
      resource: Low
      size: true
    type: web-wizard-db
status: {}
