apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 29d771d32af584ecf675dddda0e299e521a9c7d9
  application.deploy.reform/deploymentNo: qc-trial-002-local-approval_DP5
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: qc-trial-002
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-trial-002
  application.deploy.reform/revision: 2023.04.5
  deploy.reform/domain: ""
  deploy.reform/version: e81b9acf0e7ba35a992597ab6fb5d5564a7895b8
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
