apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 1a8bb879d9f772b5404ab7f930717ee78392edf7
  application.deploy.reform/deploymentNo: qc-trial-002-local-approval_DP3
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: qc-trial-002
  application.deploy.reform/repository: https://github.com/lilian-resolve/test-de-001
  application.deploy.reform/repositoryPath: qc-trial-002
  application.deploy.reform/revision: 2023.04.3
  deploy.reform/domain: ""
  deploy.reform/version: c5bd33c126af95320d9d4ca06e6b80718af3c856
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
